"use client";


import localFont from "next/font/local";
import "./globals.css";
import "@uploadthing/react/styles.css";
import { useRouter } from 'next/navigation';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
//
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

	const router = useRouter();

	const go_to_NewProductScreen = ()=>{
        	router.push('/new');
	}
 
	const go_to_AllProductsScreen = ()=>{
        	router.push('/products');
	}






  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
	<div className="button_container">
			<div className="button" onClick={()=>{ go_to_AllProductsScreen() }}>All Products</div>	
			<div className="button" onClick={()=>{ go_to_NewProductScreen() }}>New Product </div>
	</div>	
        {children}
      </body>
    </html>
  );
}
